
dataset:
    ext_op_transform_idx: 1
    transforms:
    - DecodeImage:
            img_mode: BGR
            channel_first: false
    - RecConAug:
        prob: 0.5
        ext_data_num: 2
        image_shape: [48, 320, 3]
        max_text_length: 40
    - RecAug:
    - RecResizeImg:
        image_shape: [3, 48, 320]

