global:
    max_text_length: 60
    character_dict_path: "./utils/vi_dict.txt"
    use_space_char: True
dataset:
    ext_op_transform_idx: 1
    transforms:
    - DecodeImage:
            img_mode: BGR
            channel_first: false
    - RecConAug:
        prob: 0.5
        ext_data_num: 2
        image_shape: [32, 480, 3]
        max_text_length: 60
    - RecAug: null
    - CTCLabelEncode:
    - RecResizeImg:
        image_shape: [3, 32, 480]



